spring:
  application:
    name: ecommerce-eureka
  profiles:
    active: ${SPRING_PROFILE:local}
server:
  port: ${EUREKA_PORT:8282}
eureka:
  instance:
    hostname: ${EUREKA_INSTANCE_HOSTNAME:localhost}
    metadataMap:
      instanceId: ${spring.application.name}:${server.port}
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/