spring:
  application:
    name: configserver
  security:
    user:
      name: cmw
      password: pocEcomCMW
  profiles:
    active: ${SPRING_PROFILE:local}
  cloud:
    config:
      server:
        git:
          uri: https://github.com/cmv-teknoloji/config-repo
          searchPaths: '{application}'
          force-pull: true
          clone-on-start: true
server:
  port: 0
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8282/eureka}
  instance:
    preferIpAddress: true
    instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}