spring:
  application:
    name: ecommerce-config-server
  security:
    user:
      name: cmw
      password: pocEcomCMW
  profiles:
    active: ${SPRING_PROFILE:local}
  cloud:
    config:
      server:
        git:
          uri: https://github.com/cmv-teknoloji/config-repo
          searchPaths: '{application}'
          force-pull: true
          clone-on-start: true