/**
 * WsReportWithReferenceServices.java
 *
 * This file was auto-generated from WSDL
 * by the Apache Axis 1.4 Apr 22, 2006 (06:55:48 PDT) WSDL2Java emitter.
 */

package tr.com.yurticikargo.sswIntegrationServices;

public interface WsReportWithReferenceServices extends java.rmi.Remote {
    public tr.com.yurticikargo.sswIntegrationServices.DeliveryCollectionDataResponseVO getDeliveryCollectionInfoByReference(java.lang.String userName, java.lang.String password, java.lang.String language, java.lang.String startDate, java.lang.String endDate, java.lang.String dateType, java.lang.String[] custDocNumber, long[] custId, java.lang.String subCustomer) throws java.rmi.RemoteException, tr.com.yurticikargo.WSExceptions.YurticikargoWSException;
    public tr.com.yurticikargo.sswIntegrationServices.ShippingDataV3ResponseVO listInvDocumentByCustIdV2(java.lang.String userName, java.lang.String password, java.lang.String language, tr.com.yurticikargo.sswIntegrationServices.CustParamsVO custParamsVO, tr.com.yurticikargo.sswIntegrationServices.UnitParamsVO unitParamsVO, java.lang.String subCustomerFlag, java.lang.String startDate, java.lang.String endDate, java.lang.String dateParamType, java.lang.String wsUserGroupId, java.lang.String withCargoLifecycle) throws java.rmi.RemoteException, tr.com.yurticikargo.WSExceptions.YurticikargoWSException;
    public tr.com.yurticikargo.sswIntegrationServices.ShippingDataResponseVO listInvDocumentByGrpSpecialField(java.lang.String userName, java.lang.String password, java.lang.String language, tr.com.yurticikargo.sswIntegrationServices.CustParamsVO custParamsVO, java.lang.String fieldName, java.lang.String[] fieldValueArray, java.lang.String startDate, java.lang.String endDate, java.lang.String dateParamType, java.lang.String withCargoLifecycle) throws java.rmi.RemoteException, tr.com.yurticikargo.WSExceptions.YurticikargoWSException;
    public tr.com.yurticikargo.sswIntegrationServices.ShippingDataResponseVO listInvDocumentByWaybillNo(java.lang.String userName, java.lang.String password, java.lang.String language, tr.com.yurticikargo.sswIntegrationServices.CustParamsVO custParamsVO, java.lang.String[] waybillNoArray, java.lang.String startDate, java.lang.String endDate, java.lang.String dateParamType, java.lang.String withCargoLifecycle) throws java.rmi.RemoteException, tr.com.yurticikargo.WSExceptions.YurticikargoWSException;
    public tr.com.yurticikargo.sswIntegrationServices.ShippingDataResponseVO listInvDocumentInterfaceByReference(java.lang.String userName, java.lang.String password, java.lang.String language, tr.com.yurticikargo.sswIntegrationServices.CustParamsVO custParamsVO, java.lang.String fieldName, java.lang.String[] fieldValueArray, java.lang.String[] docIdArray, java.lang.String startDate, java.lang.String endDate, java.lang.String dateParamType, java.lang.String withCargoLifecycle) throws java.rmi.RemoteException, tr.com.yurticikargo.WSExceptions.YurticikargoWSException;
    public tr.com.yurticikargo.sswIntegrationServices.ShippingDataV2ResponseVO listInvDocumentInterfaceWithFailedDeliveryV2(java.lang.String userName, java.lang.String password, java.lang.String language, tr.com.yurticikargo.sswIntegrationServices.CustParamsVO custParamsVO, java.lang.String fieldName, java.lang.String departureUnitId, java.lang.String startDate, java.lang.String endDate, java.lang.String dateParamType) throws java.rmi.RemoteException, tr.com.yurticikargo.WSExceptions.YurticikargoWSException;
    public tr.com.yurticikargo.sswIntegrationServices.XShippingV2ResponseVO listNgiShipping(java.lang.String userName, java.lang.String password, java.lang.String language, tr.com.yurticikargo.sswIntegrationServices.CustParamsVO custParamsVO, java.lang.String fieldName, java.lang.String[] fieldValueArray, java.lang.String[] docIdArray, java.lang.String startDate, java.lang.String endDate, java.lang.String dateParamType, java.lang.String withCargoLifecycle) throws java.rmi.RemoteException, tr.com.yurticikargo.WSExceptions.YurticikargoWSException;
}
