spring:
  application:
    name: ecommerce-core
  datasource:
    password: postgres
    url: jdbc:postgresql://localhost:5432/demo
    username: postgres
  jackson:
    default-property-inclusion: non_empty
    serialization:
      indent-output: true
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE